version: 0.1

phases:
  install:
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Installing (pre build)...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - source/index.html
